Repository rfridayb/tournament-manager, pull requests merged in 2023-01, with the labels that each got.

#25 Repository & service
  src/main/java/fr/sdv/gweltaz/tournamentmanager/DTO/PageDto.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/DTO/PaginationContext.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Repository/PlayerRepository.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Repository/TeamRepository.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Repository/TournamentRepository.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/PlayerService.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/TeamService.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/TournamentService.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/impl/PlayerServiceImpl.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/impl/TeamServiceImpl.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/impl/TournamentServiceImpl.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/mapper/PageMapper.java
Labels: enhancement

#26 Add ControllerAdvice and basic error codes
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Controller/BaseAdvice.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Exception/IdMismatchException.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Exception/ResourceNotFoundException.java
  src/main/resources/.gitignore
  src/main/resources/application.properties
Labels: enhancement

#27 Controllers/tournament
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Controller/BaseAdvice.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Controller/TournamentController.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/DTO/ErrorCodeEnum.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/DTO/TournamentStateUpdateDTO.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Exception/NoWinnerException.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/TeamService.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/TournamentService.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/impl/TeamServiceImpl.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/impl/TournamentServiceImpl.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/mapper/TournamentMapper.java
Labels: enhancement

#29 Add player controller
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Controller/PlayerController.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/DTO/PlayerNameDTO.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Repository/PlayerRepository.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/PlayerService.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/impl/PlayerServiceImpl.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/mapper/PlayerMapper.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/mapper/TeamMapper.java
  tournament-manager.log.2022-11-14.0.gz
  tournament-manager.log.2022-11-15.0.gz
  tournament-manager.log.2022-11-16.0.gz
Labels: enhancement

#30 Add team controller
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Controller/TeamController.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/DTO/TeamWithStatsDTO.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Repository/TeamRepository.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/TeamService.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/impl/TeamServiceImpl.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/mapper/PlayerMapper.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/mapper/TeamMapper.java
  tournament-manager.log.2023-01-04.0.gz
Labels: enhancement

#32 Add features to Tournament Controller
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Controller/TournamentController.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/TournamentService.java
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Service/impl/TournamentServiceImpl.java
Labels: bug

#33 Fix DTO returned by getTournamentDetails method in TournamentController
  src/main/java/fr/sdv/gweltaz/tournamentmanager/Controller/TournamentController.java
Labels: invalid
